add signIn form
Troshuk/water-tracker-app pull request #1
Opened 2024-04-12 10:09 UTC by deathfluffy

2024-04-12 15:04 UTC, Troshuk requested changes

2024-04-12 15:04 UTC, Troshuk commented on src/components/ForgotPassword/ForgotPassword.jsx
> +    <div>
тут заміни 
```html
<div> на <Section><Container><h1>Forgot Password</h1></Container></Section>
```

2024-04-12 15:04 UTC, Troshuk commented on src/components/ForgotPassword/ForgotPassword.jsx
> +const ForgotPassword = () => {
тут роби просто експорт, не дефолтний

2024-04-12 15:04 UTC, Troshuk commented on src/components/ForgotPassword/ForgotPassword.module.css
Якщо стоврив файл то і імпортуй його

2024-04-12 15:04 UTC, Troshuk commented on src/components/LoginFrom/Demo.jsx
> +export const CssTextField = styled(TextField)(({ theme }) => ({
Я так розумію що це поле може бути перевикористаним у інших формах, тому назви цей компонент щось в плані FormTextField і нехай буде як окрепий компонент який будеш імпортувати де портібно.

2024-04-12 15:04 UTC, Troshuk commented on src/components/ForgotPassword/ForgotPassword.jsx
Також додай цей компонент до екпортів інших компонентів у index.js

2024-04-12 15:04 UTC, Troshuk commented on src/components/ForgotPassword/ForgotPassword.jsx
> +import React from 'react';
React тут не потрібен

2024-04-12 15:04 UTC, Troshuk commented on src/pages/ForgotPasswordPage.jsx
> +export default function ForgotPasswordPage() {
додай пусту строку після імпорта перед функцією

2024-04-12 15:11 UTC, Troshuk commented on src/components/LoginFrom/LoginFrom.jsx
> +    <div className={css.loginContainer}>
```html
<div> на <Section><Container>></Container></Section>
```

2024-04-12 15:12 UTC, Troshuk commented on src/components/FormTextField/Demo.jsx
Зміни назву на більш логічну константи та назви файлу

2024-04-12 15:13 UTC, Troshuk commented on src/components/LoginFrom/LoginFrom.jsx
> -      <Container className={css.loginContainer}>
Секцію та контейнер залиш, вони роблять центрування і обмеження по ширині

2024-04-17 13:56 UTC, deathfluffy commented on src/components/LoginFrom/LoginFrom.module.css
Там проблема з позиціонуванням LoginForm на desktop

2024-04-17 21:18 UTC, Troshuk approved these changes

2024-04-17 21:18 UTC, merged